Fortran oo support
jameskermode/f90wrap pull request #239
Opened 2024-12-05 09:55 UTC by danbeibei

2024-12-05 12:47 UTC, danbeibei commented
@jameskermode I'm not sure what is wrong with the builds, could you help me figure out?

2024-12-06 13:59 UTC, krystophny commented
@danbeibei this looks great! Looks like we did some work in parallel in #233 and #236 in the last week (what a coincidence). Does this already allow also allocatable output of polymorphic class instances in factory procedures? If yes, did you follow the same strategy of wrapping a class into another type container? It would be great if we could cross-check our example cases in the each others branch and then see how to proceed with merging.

2024-12-20 15:19 UTC, danbeibei commented
Hi @krystophny, great stuff! No, it does not allow allocatable output. I have rapidly checked out the examples in your branch and can confirm my changes do not actually address what you changes do. I'll take the time in a few weeks to have a look into the code you pushed.

2024-12-26 20:30 UTC, krystophny commented
@danbeibei @jameskermode I have now summarized all PRs on #240 in order, rebased mine on top of this one here, and merged everything in master of https://github.com/itpplasma/f90wrap for testing until you could dig through the reviews. Until then, happy holidays!

2024-12-26 20:40 UTC, krystophny commented on pyproject.toml
> +dependencies = ["numpy>=1.13", "packaging", "pytest", "pytest-dependency"]
Two questions here:

1) Should `pytest-dependency` really be used? Avoiding dependencies between tests is usually considered good practice.
2) If 1) can be avoided, is `pytest` even necessary, or better stick to good old `unittest` (I rewrote mine after realizing that `pytest` is not a requirement)?

2025-01-03 10:41 UTC, jameskermode commented on pyproject.toml
> +dependencies = ["numpy>=1.13", "packaging", "pytest", "pytest-dependency"]
I would indeed prefer to stick to unittest and avoid adding dependencies if possible

2025-01-03 12:16 UTC, jameskermode requested changes
Happy to merge this if the pytest dependency can be removed

2025-01-06 11:23 UTC, jameskermode commented
Merging since remaining issues will be fixed by #243 to be merged next

2025-01-06 11:23 UTC, merged